[workspace]
members = [
    "course/*/*/chapter-examples",
    "exercises/*"
]

resolver = "3"

[workspace.dependencies]
bevy = "0.17"
leafwing-input-manager = { version = "0.18" }
clap = { version = "4.5", features = ["derive"] }
wayland-sys = { version = "0.31", features = ["dlopen"] }